// =============================================================
// PWA · Service Worker registration + auto-update banner
// -------------------------------------------------------------
// Registers the service worker (generated by vite-plugin-pwa).
// Shows a banner when a new version is detected, asking the user
// whether to update now or later.
// =============================================================

export function initPWA() {
  import('virtual:pwa-register').then(({ registerSW }) => {
    const updateSW = registerSW({
      // 检测到新版本时弹出更新横幅（用户决定是否更新）
      onNeedRefresh() {
        showUpdateBanner(() => updateSW(true));
      },
      // 首次安装完成、可离线使用时提示
      onOfflineReady() {
        if (typeof window.showToast === 'function') {
          window.showToast('✅ 已离线可用');
        }
      },
      // 注册成功后，每小时主动检查一次更新（防止 app 长时间不刷新）
      onRegisteredSW(swUrl, registration) {
        if (!registration) return;
        // 立即检查一次（0.5s 后，避开冷启动竞争）
        setTimeout(() => registration.update().catch(() => {}), 500);
        // 之后每小时检查一次
        setInterval(() => registration.update().catch(() => {}), 60 * 60 * 1000);
        // 切回标签页/窗口聚焦时也检查
        document.addEventListener('visibilitychange', () => {
          if (!document.hidden) registration.update().catch(() => {});
        });
        window.addEventListener('focus', () => registration.update().catch(() => {}));
      },
    });
  }).catch(() => { /* dev mode or SW unavailable */ });
}

function showUpdateBanner(onConfirm) {
  if (document.getElementById('pwa-update-banner')) return;
  const bar = document.createElement('div');
  bar.id = 'pwa-update-banner';
  bar.style.cssText = `
    position: fixed; left: 50%; bottom: 24px; transform: translateX(-50%);
    background: rgba(28,28,48,0.96); backdrop-filter: blur(16px);
    color: white; padding: 12px 18px; border-radius: 14px;
    border: 1.5px solid rgba(255,255,255,0.18);
    box-shadow: 0 8px 32px rgba(0,0,0,0.45);
    z-index: 99999; display: flex; align-items: center; gap: 12px;
    font-size: 13px; font-family: inherit;
    animation: pwaBannerIn 0.35s ease;
  `;
  bar.innerHTML = `
    <span>🎉 心流有新版本</span>
    <button id="pwa-update-yes" style="background:rgba(120,200,255,0.25);border:1px solid rgba(120,200,255,0.5);color:white;padding:5px 12px;border-radius:8px;font-size:12px;font-weight:600;cursor:pointer;font-family:inherit;">立即更新</button>
    <button id="pwa-update-no"  style="background:none;border:none;color:rgba(255,255,255,0.5);font-size:12px;cursor:pointer;font-family:inherit;padding:4px 6px;">稍后</button>
  `;
  document.body.appendChild(bar);
  if (!document.getElementById('pwa-banner-keyframes')) {
    const st = document.createElement('style');
    st.id = 'pwa-banner-keyframes';
    st.textContent = `@keyframes pwaBannerIn { from { opacity:0; transform:translate(-50%, 16px); } to { opacity:1; transform:translate(-50%, 0); } }`;
    document.head.appendChild(st);
  }
  document.getElementById('pwa-update-yes').onclick = () => { bar.remove(); onConfirm(); };
  document.getElementById('pwa-update-no').onclick  = () => { bar.remove(); };
}
